=== erickimme/migrating-from-pusher-chatkit/example-chatkit-data-export/schema/message.json
{
    "$id": "https://pusher.com/schema/chatkit/message.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "A Chatkit message",
    "type": "object",
    "properties": {
      "id": {
        "type": "number",
        "description": "A unique id for the message"
      },
      "sender_id": {
        "type": "string",
        "description": "The ID of the user who sent the message"
      },
      "room_id": {
        "type": "string",
        "description": "The ID of the room that the message belongs to"
      },
      "created_at": {
        "type": "string",
        "format": "date-time",
        "description": "Timestamp of the entity creation"
      },
      "updated_at": {
        "type": "string",
        "format": "date-time",
        "description": "The last time the entity was updated"
      },
      "parts": {
        "type": "array",
        "description": "The parts of the message",
        "items": {
          "anyOf": [
            {
              "type": "object",
              "properties": {
                "part_type": {
                  "const": "inline",
                  "description": "The type of the part, one of \"inline\", \"url\", or \"attachment\""
                },
                "payload": {
                  "type": "object",
                  "description": "Payload of an inline part",
                  "properties": {
                    "type": {
                      "type": "string",
                      "descripton": "The MIME type of the content of this part"
                    },
                    "content": {
                      "type": "string",
                      "descripton": "The content of this part"
                    }
                  },
                  "required": ["type", "content"]
                }
              },
              "required": ["part_type", "payload"]
            },
            {
              "type": "object",
              "properties": {
                "part_type": {
                  "const": "url",
                  "description": "The type of the part, one of \"inline\", \"url\", or \"attachment\""
                },
                "payload": {
                  "type": "object",
                  "description": "Payload of a URL part",
                  "properties": {
                    "type": {
                      "type": "string",
                      "descripton": "The MIME type of the resource that the URL points to"
                    },
                    "url": {
                      "type": "string",
                      "descripton": "A URL"
                    }
                  },
                  "required": ["type", "url"]
                }
              },
              "required": ["part_type", "payload"]
            },
            {
              "type": "object",
              "properties": {
                "part_type": {
                  "const": "attachment",
                  "description": "The type of the part, one of \"inline\", \"url\", or \"attachment\""
                },
                "payload": {
                  "type": "object",
                  "description": "Payload of an attachment part",
                  "properties": {
                    "type": {
                      "type": "string",
                      "descripton": "The MIME type of the attachment"
                    },
                    "name": {
                      "type": "string",
                      "descripton": "The name of the attached file"
                    },
                    "size": {
                      "type": "number",
                      "description": "The size of the attached file in bytes"
                    },
                    "custom_data": {
                      "description": "Arbitrary custom data associated with the file at upload"
                    }
                  },
                  "required": ["type", "name", "size", "download_url"]
                }
              },
              "required": ["part_type", "payload"]
            }
          ]
        }
      }
    },
    "required": ["id", "sender_id", "room_id", "created_at", "updated_at", "parts"]
  }

=== erickimme/migrating-from-pusher-chatkit/_input/messages.json
[
  {
    "id": 42,
    "sender_id": "alice",
    "room_id": "alice_x_bob",
    "created_at": "2020-03-25T12:52:59Z",
    "updated_at": "2020-03-25T12:52:59Z",
    "parts": [
      {
        "part_type": "inline",
        "payload": {
          "type": "text/plain",
          "content": "Hello Bob!"
        }
      },
      {
        "part_type": "url",
        "payload": {
          "type": "image/png",
          "url": "https://example.com/hello_world.png"
        }
      },
      {
        "part_type": "attachment",
        "payload": {
          "type": "video/mp4",
          "name": "hello.mp4",
          "size": 42,
          "download_url": "https://example.com/hello.mp4",
          "custom_data": {
            "foo": "bar"
          }
        }
      }
    ]
  },
  {
    "id": 43,
    "sender_id": "bob",
    "room_id": "bob_x_carol",
    "created_at": "2020-03-25T12:52:59Z",
    "updated_at": "2020-03-25T12:52:59Z",
    "parts": [
      {
        "part_type": "inline",
        "payload": {
          "type": "text/plain",
          "content": "Hello Carol!"
        }
      }
    ]
  },
  {
    "id": 43,
    "sender_id": "carol",
    "room_id": "general",
    "created_at": "2020-03-25T12:52:59Z",
    "updated_at": "2020-03-25T12:52:59Z",
    "parts": [
      {
        "part_type": "inline",
        "payload": {
          "type": "text/plain",
          "content": "Hello Everyone!"
        }
      }
    ]
  }
]
