=== erickimme/migrating-from-pusher-chatkit/example-chatkit-data-export/schema/user.json
{
    "$id": "https://pusher.com/schema/chatkit/user.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "A Chatkit user",
    "type": "object",
    "properties": {
      "id": {
        "type": "string",
        "description": "A unique id for the user"
      },
      "name": {
        "type": "string",
        "description": "Room name / title"
      },
      "avatar_url": {
        "type": "string",
        "description": "A link to the userâ€™s photo/image"
      },
      "custom_data": {
        "type": "object",
        "description": "Custom data associated with the entity"
      },
      "created_at": {
        "type": "string",
        "format": "date-time",
        "description": "Timestamp of the entity creation"
      },
      "updated_at": {
        "type": "string",
        "format": "date-time",
        "description": "The last time the entity was updated"
      }
    },
    "required": ["id", "name", "created_at", "updated_at"]
}

=== erickimme/migrating-from-pusher-chatkit/_input/users.json
[
  {
    "id": "alice",
    "name": "Alice",
    "avatar_url": "https://example.com/alice.png",
    "custom_data": {
      "foo": "bar"
    },
    "created_at": "2020-03-25T10:52:07Z",
    "updated_at": "2020-03-26T15:59:50Z"
  },
  {
    "id": "bob",
    "name": "Bob",
    "created_at": "2020-03-25T10:52:15Z",
    "updated_at": "2020-03-25T10:52:15Z"
  },
  {
    "id": "carol",
    "name": "Carol",
    "created_at": "2020-03-25T10:52:59Z",
    "updated_at": "2020-03-25T10:52:59Z"
  }
]
